compressionLevel: 9

enableGlobalCache: true

installStatePath: .yarn/install-state.gz

logFilters:
  - code: YN0013
    level: discard

nmMode: hardlinks-local

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.1.cjs
