openapi: 3.0.0
info:
  title: Sadhana Tracker API
  description: Sadhana Tracker API
  version: 1.0.0

paths:

  /auth/login:
    post:
      $ref: "./endpoints/auth.yaml#/login"

  /auth/register:
    post:
      $ref: "./endpoints/auth.yaml#/register" 
